### ISSUE TITLE
ECS ASG scaling rules

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#10]
After #120, add some scaling rules to the prod ASG based on CPU/Memory reservation.  Something like ... always have 1 at least half-empty instance around.

Will also require some CFN changes to prevent resetting the ASG DesiredCount every time we deploy.

Then, can tackle #134 and #135.

**Comment by kookster** [comment]
Estimating getting this figured out for fancy prod cluster, for dovetail and feeder apps.
