### ISSUE TITLE
Review DNS records that were not migrated from Contegix to CloudFormation

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#107]
The XXXXX section of this gist https://gist.github.com/farski/61c4a9f85a590d930c96350d7a8b0c08

**Comment by kookster** [comment]
Reviewing them here:

https://docs.google.com/a/prx.org/spreadsheets/d/1ormMW21wXXoUpjOoqDA8gdNVeS01aZNlZoJKBOkNyaE/edit?usp=sharing
