### ISSUE TITLE
Compare current public DNS records to deployed records on Infrastructure

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#108]
This could be automated or manual. The key things to look for are making sure all the records that are marked as migrated https://gist.github.com/farski/61c4a9f85a590d930c96350d7a8b0c08 are in fact migrated, and the names and values are correct.

**Comment by farski** [comment]
I have a solution for this, so it can be done as soon as we finalize the records that we want to keep/remove.

**Comment by farski** [comment]
Missing these

MISMATCH:podcast.prx.org 		 ZON:199.119.122.230 		 CNX:199.119.122.230 		 AWS:
90 MISMATCH:podcasts.prx.org 		 ZON:199.119.122.230 		 CNX:199.119.122.230 		 AWS:
91 MISMATCH:widgetsdemo.prx.org 		 ZON:199.119.122.230 		 CNX:199.119.122.230 		 AWS:
92 MISMATCH:www.podcast.prx.org 		 ZON:199.119.122.230 		 CNX:199.119.122.230 		 AWS:
93 MISMATCH:www.podcasts.prx.org 		 ZON:199.119.122.230 		 CNX:199.119.122.230 		 AWS:
94 MISMATCH:saltcast.prx.org 		 ZON:199.119.122.230

**Comment by farski** [comment]
Double check this one

178 MISMATCH:assets1.prx.org 		 ZON:d11pcyef3meeu9.cloudfront.net 		 CNX:d11pcyef3meeu9.cloudfront.net. 		 AWS:52.85.101.84


I suspect it's because I made it an Alias record

**Comment by farski** [comment]
Missing 187 MISMATCH:youthradioleaders.prx.org 		 ZON:youthradioleaders.prx.org.s3-website-us-east-1.amazonaws.com 		 CNX:youthradioleaders.prx.org.s3-website-us-east-1.amazonaws.com. 		 AWS:

**Comment by gcampo88** [comment]
checked as well and found the same list of mismatches as you have in your last three comments on this, @farski  (plus google calendar, which we're ignoring)

**Comment by gcampo88** [comment]
update: after new changes, only assets1.prx.org still mismatching out of above list.
