### ISSUE TITLE
Switch name servers for prx.org

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#109]
From Contegix to Route 53

**Comment by pkarman** [comment]
@farski is this an Epic encompassing tasks like #107 and #108? Or is this the actual flip-the-switch task?

**Comment by farski** [comment]
@pkarman the actual switch

**Comment by pkarman** [comment]
Cool. Seems like a size Medium Estimate then?

**Comment by farski** [comment]
I guess I included a fair amount of testing in that, and assumed it will be something several people are on deck for. The actual switch is ~30s of work.
