### ISSUE TITLE
Determine cluster instance sizing per environment type

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#11]

**Comment by farski** [comment]
Would be good to make sure we feel good about where we've landed with this.

**Comment by cavis** [comment]
We should check our costs.  As far as stability, running large instances for ECS, and 2x standalone nginx caches works great.  I'd prefer to stick with this, if it's not cost prohibitive.  (Especially if we get > 1 DT running on each instance, we can trim down the cluster size quite a bit).

**Comment by cavis** [comment]
Yep!
