### ISSUE TITLE
Dovetail multiple-tasks-per-instance

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#110]
Allow DT to run multiple tasks per instance (currently limited to 1-per-instance).  This simplifies all sorts of things (auto-scaling, ECS-instance counts, etc).

I _think_ this will involve recreating the service, which may or may not result in an outage while the ALB moves the route from one target group to another.  Will need to very carefully test this out in staging.

**Comment by farski** [comment]
@cavis Remind me what's keeping this from happening right now?

**Comment by cavis** [comment]
Originally, we were seeing network issues trying to run > 1 dovetail on a `t2` instance.  I'm _guessing_ that some of that was us burning through CPU credits too fast under load.  Now that we're on non-burst instances, I'm hoping that won't be a problem.  (Though we should be careful about testing that).

The only thing stopping us from testing is the possibility that CFN will tear down too much of dovetail in order to create a new service without the "1 per instance" placement rule.

(Probably a few other misc updates to make around the DT-monitoring/killing lambdas, and making sure we have enough disk space for that many tasks).

**Comment by cavis** [comment]
Deployed, updated lambdas/dashboards, and seems to be working fine.  Calling this good.
