### ISSUE TITLE
Refactor notifications framework

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#115]
The monolith `sns-ops-to-slack` lambda is getting bloated and should be broken up.

**Comment by pkarman** [comment]
@farski Estimate?

**Comment by farski** [comment]
@pkarman This appears to already have an estimate from a few days ago. Or I'm doing estimates wrong.

**Comment by pkarman** [comment]
ah you're right - sorry. All set.

**Comment by farski** [comment]
All triggers have been removed from the snsopstoslack function, so I think that indicates this is mostly done. There are still a few lingering issues that need to be resolved with messages getting sent to the log-level SNS topics that aren't cloudwatch alarms

**Comment by farski** [comment]
This is done aside from #152 so I'm closing it. The only messages getting sent to log-level topics (that shouldn't be) are those coming from nested CloudFormation stacks whose `NotificationARNs` are not being updated as expected from their parent stack. I have filed a support ticket with AWS to try to get it sorted out.
