### ISSUE TITLE
Fix up Upload Lambda

### ISSUE THREAD

**Issue by gcampo88** [PRX/Infrastructure#118]
~`upload.prx.org.yml` is filled out and the stack info is written in root.yml, but currently commented out because the deploy failed with this error message:
`"Your access has been denied by S3, please make sure your request credentials have permission to GetObject for prx-infrastructure-us-east-1-application-code/lambda/PRX-upload.prx.org.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied " on the Create for UploadLambdaFunction`~
~Investigate permissions (in cd.yml?) for GetObject for this new bucket, which was added today; once that's sorted, comment the upload lambda back in and get it into cicd.~
Permissions issue has been sorted! Next step is adding custom domain. @farski anything else you can think of to go in here?

**Comment by gcampo88** [comment]
Setting as a 2 because of ever-present CF unknowns

**Comment by farski** [comment]
Not entirely sure what this was for, but we've deployed this so I'm guessing it got sorted out at some point.
