### ISSUE TITLE
CI should create the ECR repo

### ISSUE THREAD

**Issue by sandikbarr** [PRX/Infrastructure#123]
When a .prxci file is added to a project, CI should create the ECR repo.

**Comment by farski** [comment]
At some point I thought there was a make-the-repo-if-it-doesnt-exist flag, but I may have been looking at the AWS push command, and we really only (as suggested) used docker push, which can't make a new ECR repo.

The way to make this happen would have to query to see if the repo exists and make it if it doesn't.`CreateRepository` always returns an error if the repo name exists

**Comment by farski** [comment]
Actually @cavis do you think there's any problem with just always executing `aws ecr create-repository` and eating the error?

**Comment by cavis** [comment]
Fine by me.  I think that's what I had in the original snap-ci script, way back when.

**Comment by farski** [comment]
@pkarman Any interest in this one? Would be a small change to [the shared build script](https://github.com/PRX/Infrastructure/blob/master/ci/utility/post_build.sh) that our apps call at the end of the CI build
