### ISSUE TITLE
Lambda deployment: CodeBuild

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#124]
Modify prxci runner:

  - [x] Recognize lambda repos (via the `.prxci` yaml config)
  - [x] Run the normal prxci stuff for PRs
  - [x] For master, also run another set of commands (via prxci yaml) that builds/zips the code, and copies into the host filesystem
  - [x] For master, copy zip to a known S3 bucket (`prx-lambda-builds/cms-audio-lambda/1234567.zip`)
  - [x] Update zip-version-shas in the `staging.zip` and `production.zip` configs, similar to what docker images do.

**Comment by farski** [comment]
This mostly seems to be working, so I'm closing. Any issues capture in new tickets
