### ISSUE TITLE
Lambda deployment: CFN Stacks

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#125]
Modify CFN stacks:

  - [ ] Add a stack for each lambda, which takes in a `ZipVersionSha` or something, which tells the stack which zipped code to use
  - [ ] ENV configs
    - Use the AWS parameter-store (there are examples of this) to pull out ENVs directly in the handler and memoize them.  We'll used non-versioned configs, where changes are propagated instantly.

**Comment by farski** [comment]
@cavis Is there any part of this we haven't figured out yet? I know param store is still WIP, but we have deployment working

**Comment by cavis** [comment]
I think we can close this.  Several lambda repos already working as expected.
