### ISSUE TITLE
Migrate prxu.org hosted zone to CloudFormation

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#129]

**Comment by farski** [comment]
Template launched. Need another set or eyes to compare to the existing zone:

Existing
https://console.aws.amazon.com/route53/home#resource-record-sets:ZN50DZ7QNP6A5

New
https://console.aws.amazon.com/route53/home#resource-record-sets:ZMIURD9R7JFJ0

One record was changed from a CNAME to A/AAA ALIAS on purpose

**Comment by kookster** [comment]
lgtm!
