### ISSUE TITLE
Migrate solr deployment to CloudFormation template

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#151]

**Comment by kookster** [comment]
I am not sure I agree this is a high priority - @farski can you explain your thinking

**Comment by farski** [comment]
I thought we were mostly going with infrastructure-as-code as the the default for getting things running on AWS, so, if that's the case, I figured it made sense to get that done now with it fresh in people's minds

**Comment by kookster** [comment]
I did not plan on doing that for every legacy service, that is going to make moving off contegix much harder.

**Comment by kookster** [comment]
to be clear - I do not expect there to be any updates to this, it is more like an RDS db than it is an application we deploy; it makes sense for exchange to be in cloud formation, I don't think solr needs to be.

**Comment by farski** [comment]
Getting stuff into a template generally shouldn't be that much harder than doing it through the API or console

**Comment by kookster** [comment]
that may be true for you ;)

**Comment by farski** [comment]
The plan is to create a CloudFormation template that can launch an EC2 instance for solr from a specific AMI. It will be launched in the data-stag and data-prod accounts, and use the existing VPCs in those that are connected to the primary app VPC

**Comment by kookster** [comment]
ok - I got the ebs disk init'd and mounted on staging, will configure dns and see if staging works now 🤞

**Comment by kookster** [comment]
worx! https://exchange.staging.prx.tech/search/pieces?q=radio

**Comment by farski** [comment]
Still a bit of work needed to finish this in production
