### ISSUE TITLE
Disable ECS cluster scaling during deploys

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#159]
When updating an ECS service (mostly just Dovetail, at the moment), the asg-sizer-lambda tends to thrash.  Presumably because there are a bunch of extra tasks floating around for a brief amount of time.

Should detect when a service is deploying (status changes maybe?) and don't do any cluster scaling until it finishes.

**Comment by farski** [comment]
We don't really use the sizer lambda anymore
