### ISSUE TITLE
Analytics lambda cutover

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#169]
Cut from the old to the new analytics-ingest lambdas.  Preventing overlap in the kinesis records will take a bit of work.

One idea (from @farski): configure a specific "stop-processing-at" timestamp in the old function's code, so the old functions will stop when `record.payload.timestamp >= STOP_AT_TIME`.  Then configure the new-function's kinesis triggers to start at that timestamp.  I've not tried starting a trigger at a timestamp, so it's not entirely clear that it's the record-payload-timestamp vs the record-timestamp.  May be safer to just also do this start-at in the code, rather than relying on the trigger.

**Comment by farski** [comment]
I actually meant doing start-at in code; forgot that could even do that with the kinesis pointer. That seems simpler/more testable

**Comment by cavis** [comment]
Yeah, you can do "start at" when configuring the pointer, but not "stop at".

Guess I'd just have to make sure the old function stops at the `record.timestamp` (not `record.payload.timestamp`).

**Comment by cavis** [comment]
Okay, so given that the kinesis `approximateArrivalTimestamp` is not quite the same as the `payload.record.timestamp` ... i've opted to do this entirely in code.

Plan:

1. Pick a set time in the future, giving myself enough time to complete these steps
2. Set `STOP_AT_EPOCH` on old functions
3. Set `START_AT_EPOCH` on new functions
4. Add kinesis trigger(s) to new functions, starting pointer at "latest" (will just log that it's skipping these for awhile)
5. When timestamp hits, old function will start logging skips, new function will start logging inserts.

**Comment by cavis** [comment]
Still some TODOs in a couple of days (just in case this breaks something):

- [ ] Delete old Lambda functions
- [ ] Remove old cloudwatch logs
- [ ] Remove old cloudwatch alarms
- [ ] Parade/fireworks
