### ISSUE TITLE
Rewrite GitHub Webhook Endpoint Lambda function in Python

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#172]
This is [fewer than 100 LOC](https://github.com/PRX/Infrastructure/blob/master/ci/lambdas/github-webhook-endpoint/index.js) and could easily be rewritten by someone with limited Python experience. The only part that isn't some basic flow control is the [checking the GitHub event signature](https://github.com/PRX/Infrastructure/blob/master/ci/lambdas/github-webhook-endpoint/index.js#L61), but Python should have a native way of handling that.

_These are being rewritten because Python Lambda functions tend to be easier to deal with._

**Comment by gcampo88** [comment]
I'd be interested in trying this! With caveat that since I don't know Python, it is certain to take me longer than someone who does.

**Comment by farski** [comment]
This is somewhat less important now that Node 8 is supported, and lambdas can be written without callbacks

**Comment by cavis** [comment]
You can take my callbacks when you pry them from my cold, dead hands.

**Comment by farski** [comment]
#431 rewrote this function in modern Node, so this is no longer necessary
