### ISSUE TITLE
Get unpaginated alarm history from CW

### ISSUE THREAD

**Issue by gcampo88** [PRX/Infrastructure#199]
We recently noticed that the "Last 24 hours" alarm count in Slack never exceeded 25. Hypothesis: we're getting paginated results from our `cloudwatch.describe_alarm_history` call [in the alarm notifications lambda](https://github.com/PRX/Infrastructure/blob/master/notifications/lambdas/cloudwatch-alarm-notification-handler/lambda_function.py#L49). 

 Per [Cloudwatch](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/describe-alarm-history.html): `describe-alarm-history is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results. You can disable pagination by providing the --no-paginate argument.`

**Comment by farski** [comment]
I've bumped the `MaxRecords` on this API call to `100`. I don't think it's worth iterating over pages beyond that (if an alarm has already trigger 100x in 24 hours we likely know there's an issue).
