### ISSUE TITLE
Revert prx.org hosted zone to CloudFormation version

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#238]
Currently the zone records are out of sync with the stack

**Comment by kookster** [comment]
@cavis is this still the case?

**Comment by farski** [comment]
![image](https://user-images.githubusercontent.com/3483/41860127-cff55c06-786b-11e8-9cf2-95f95898fe3b.png)
The most recent events on the stack is still a rollback, so something wasn't happy the last time it tried to deploy

**Comment by cavis** [comment]
Erg... yeah.  I'll take a TODO to get this done tonight.

**Comment by cavis** [comment]
I'll even set an alarm on my phone!

**Comment by farski** [comment]
One worst case solution would be just spin up a new hosted zone and swap the name servers.

**Comment by cavis** [comment]
Success!  Had to do it in 2 steps ... delete the old A record, then add the CNAME.  Time between was ~3 minutes, so _hopefully_ shouldn't impact too many people.
