### ISSUE TITLE
Parameter MasterUsername should NOT exist with DBSnapshotIdentifier for Resources/MasterDB/Properties

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#240]
In `db/mysql-instance.yml` the `DBSnapshotIdentifier` value is conditional, and it seems like in cases where it resolves to something other than `AWS::NoValue`, the `MasterUsername` and `MasterUserPassword` shouldn't exist, but at the moment they always exist. I think we may just need to make them inversely conditional to `DBSnapshotIdentifier`.

**Comment by pkarman** [comment]
@farski is this in progress? I see it in the sprint but no assignee.

**Comment by farski** [comment]
Not in progress by me. I haven't really done any of that DB work what I'd need to do a good amount of research to know what's going on here

**Comment by pkarman** [comment]
AWS reporting as an error.

**Comment by pkarman** [comment]
Maybe @sandikbarr will have some insight as to syntax improvements? Leaving unassigned for group effort.
