### ISSUE TITLE
New ECS ARN and Resource IDs

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#278]
https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/

Will become mandatory 1 Jan. 2020 for new resources. Upgrading existing resources gets better tagging and per-service and per-task cost tracking.

**Comment by farski** [comment]
https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-ecs-and-aws-fargate-now-allow-resources-tagging-/

**Comment by cavis** [comment]
Okay, so I've gone through the active lambdas (the ones in Infrastructure and a few others), and everything _should_ be okay with this change.  The service/task/container ARNs get passed around to various API calls but never altered.  I have a few one-off scripts locally that this may break, but that's fine.

Planning to opt-in to this tomorrow morning, when I can watch ECS deploys / autoscaling.  Just in case!

**Comment by cavis** [comment]
Updated defaults on the prx-legacy account.  Nothing broke!
