### ISSUE TITLE
Parameter limit on root stacks

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#348]
~We currently have 59 parameters, and there's a limit of 60~

See below; the limit has been increased to 200.

**Comment by farski** [comment]
Down to 57 once #349 gets merged

**Comment by farski** [comment]
56 if #350 works out

**Comment by farski** [comment]
One option for eliminating this limitation long term is to switch to Parameter Store (SSMPS) for the values that we currently manage through the root stack template config (e.g., ECR image tags, AWS Secrets versions, etc). By using SSMPS, those app-specific values would no longer need to be parameters of the root stack. They would only need to be parameters of the stack in which they are actually used.

Example: The CMS task definition relies on a `EcrImageTag` parameter, which is defined as a parameter on the `CmsStack`. In order for that value to get there, it's currently passed in as a parameter on the root stack, then passed as a parameter to the `ContainerAppsRootStack`, then to the `CmsStack`. With SSMPS, that parameter would only need to exist on the `CmsStack`. The value would be passed in from the `ContainerAppsRootStack`, but that's the first time it would show up in the chain (ie, the value would be a parameter once, rather than the current three times)

With this approach, the 60 parameter limit would become essentially a per-app limit, and the number of root stack parameters we actually use would decrease dramatically.

There are several significant implications that come along with this change.

**1. Staging deployment** – Currently when a new version of an app is ready to be deployed, the artifact ID (like the ECR image tag) is updated in the _staging stack template config file_. This is generally done by CI (a Lambda) as part of the build process. Changes to that file trigger CD pipeline executions.

Under the new system, the CI Lambda would update the values in SSMPS rather than the config file (which IMO feels cleaner, since it's an API call, and not downloading/parsing/rewriting/uploading a file). CI could then trigger a pipeline execution manually to maintain that workflow. 

**2. Production deployment** – Currently when a production deploy happens, some subset of values that are present in the staging template config file are promoted to the production template config file. This includes things like ECR image tags and S3 version IDs used for Lambda functions (the artifacts that represent app code versions), but not things like Secrets versions (which are environment specific). This is also a download/parse/rewrite/upload sort of system accomplished by a Lambda, and relies on pattern matching to detect which values to promote.

Under the new system, promoting values from staging to production would happen in a similar sort of way. A list of all the SSMPS values would be collected, and based on some criteria (pattern matching, tags, etc), certain values would be pushed to their production counterpart. 

**3. State capture & rollback** – This is most significantly impacted by the change. Currently to atomically capture the state of the system for any given deploy, we capture two values: the git SHA of the Infrastructure repo used for the deploy (thus capturing the state of all CloudFormation templates), and the S3 version ID of the production template config file (thus capturing the state of all app code versions: image tags, Secrets versions, etc).

eg `{ "InfrastructureSHA": "a7s678af", "ProductionConfigS3Version: "adufasf809asfa/fa78s6fa" }`

With those two values (assuming no loss of the data they reference), we can always recreate the state of any given deploy.

**THIS IS NOT STRICTLY TRUE**, even today. Because we do have some deployment configuration already coming from SSMPS, there is a chance that a rollback would not be 100% identical. In practice, the values we currently reference from SSMPS are static and it would be very unlikely for them to change, but it is a blindspot of the current system.

Under the new system, there would be a few options for capturing system state. They all include continue to track the Infrastructure git SHA. For capturing configuration state, we could:

A. Use SSMPS _Labels_. Eg, whenever we deploy, we label the latest version of each SSMPS with the git SHA, so they can all be referenced with some single value. There is a limit of 10 labels per version, and we have some values where a single version would be deployed 10 times (e.g., the image tag of Play likely does not change at least once for every 10 deploys). To get around that we could: either always create a new version of all parameters on every deploy, and then label the new version, or label versions until they hit the limit and then make a new version. Either way there's a limit of the 100 latest versions per parameter, so there's no case where we have a complete history of deploys just from using versions+labels. A rollback would entail getting all the values for parameters that match a given label, and resetting the parameters to those values.

B. Capture the resolved values of all the stack parameters getting their values from SSMPS parameters. This is fairly trivial: find all stacks that are descendants of the production root stack, and write the resolved values out to a file mapped to their source SSMPS parameter path (eg `{ "/prod/cms/EcrImageTag": "8adsa798a" }`. To rollback, we would update all the parameters that exist in the version of that file we're rolling back to with the values in the file, making the latest values the ones we want. This has the benefit of providing a complete history.

IMO the rollback procedure is not significantly different for A or B; both are iterating through some list and setting the value for each parameter. A has the benefit of relying solely on the SSM API, but B avoids some effort to work around the SSMPS limits, and avoids the limited history which can't be avoided with a pure SSM solution. Given how infrequently we do rollbacks, B feels more straightforward and reliable, in that it's just a file with all the values we need. They could easily be used to deploy in some situation where SSM were not available.

### Thoughts

The other working option is to move all our parameters to an S3 file that gets loaded by a CloudFormation custom resource, rather than as root stack parameters. The rest of the system would be largely unchanged, with the values being passed into nested stacks (and more nested stacks). While this option would be rather simple to implement, it starts to reinvent parts of CloudFormation and SSM.

One downside to all options that result in fewer root stack parameters is that it get difficult-to-impossible to generate deployment deltas as we do currently. Given that all these values are on the stack that we directly update, we can compare the stack to the stack changeset, and any changes will be visible. Once the parameters are moved down into the stack, there's no good way to see if or how they are changing based on the changeset of the root stack prior to it being executed. I don't think it would be difficult to approximate this functionality, by directly comparing the values between state captures, but the delta wouldn't be coming from the CloudFormation stack itself.

**Comment by farski** [comment]
A short-term option is to combine existing parameters. Most apps currently rely on two parameters: a secrets version, and a code artifact (either ECR image tag or S3 object version). Combining those values into a single parameter, and `split` effectively doubles the number of apps we can support without changing much else.

The trickiest bit of this would be in places where we automatically update values, like in the CI callback lambda. When a new version of an app builds, and CI goes to publish its ECR image tag, for example, rather than just updating a value in the staging config file, it would be updating a sub string of that value. Not the worst, but starting to get a little messy.

Also we would need to find something to `split` on that we know would never appear in a secrets version, ecr image tag, or s3 object version.

**Comment by farski** [comment]
The other long-term solution that is worth starting to think about is moving away from a single deployment stack. I think there's a lot to be gained from keeping everything together, as long as deployments are not slowing down, and we find good solutions to some of these hurdles we're running into.

But if single deploy does become untenable, there are likely good paths that split things up but don't feel dramatically different. Like maintaining a single deployment pipeline, which deploys more than one stack, like one stack for everything in our main VPC, one for miscellaneous projects, one for standalone serverless or static apps, etc.

**Comment by kookster** [comment]
for longer term, I could see using SSM / param store more, with sub stack specific params - that makes sense to me - that's what the param store is for - though I could go either way on A or B. (If B is less or similar effort, and gets more rollback history, seems better, but I'm not sure we need unlimited history or rollback.)

Building our own similar thing using secure files on s3 seems like not much better than the above.

Agreed on the short term option - but I also wonder if we do the above if that can be phased in soon enough to obviate the need to make the join/split necessary

**Comment by farski** [comment]
https://aws.amazon.com/about-aws/whats-new/2020/10/aws-cloudformation-now-supports-increased-limits-on-five-service-quotas/

**Comment by farski** [comment]
There's no longer any realistic danger here
