### ISSUE TITLE
Investigate ECS Cluster autoscaling

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#402]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-auto-scaling.html

Deprecate the asg-sizer lambda.

**Comment by farski** [comment]
>Now, tasks in the provisioning state include tasks that could not find sufficient resources on the existing instances. This means, for example, if you call the RunTask API and the tasks don’t get placed on an instance because of insufficient resources (meaning no active instances had sufficient memory, vCPUs, ports, ENIs, and/or GPUs to run the tasks), instead of failing immediately, the task will go into the provisioning state (note, however, that the transition to provisioning only happens if you have enabled managed scaling for the capacity provider; otherwise, tasks that can’t find capacity will fail immediately, as they did previously)

We have seen cases where tasks can't find capacity, so this is perhaps not configured properly=

**Comment by farski** [comment]
We've been using this on the new cluster for a while now and it hasn't caused any major issues. Any further work should be a new issue.
