### ISSUE TITLE
Make a tool for managing secrets

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#49]
WIP https://github.com/PRX/aws-secrets

**Comment by kookster** [comment]
yeah, the part missing now is to add updating the template config when the secrets are updated, and to add to the docker images to load from the secret stash when starting up

**Comment by farski** [comment]
I think the latter is covered by #39. Wanted to make sure both ends of the process had tickets

**Comment by kookster** [comment]
ok I think it is working now, but I still need to write some docs on how to save and update secrets, and we should also talk about how to handle multiple regions
