### ISSUE TITLE
Migrate Dovetail

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#62]

**Comment by cavis** [comment]
Prerequisites:

- [ ] Update prod cluster to `t2.medium`
- [ ] Update prod cluster to 72GB storage (currently using the launch config default of 22GB)
- [ ] Add user-data scripts to:
  - Monitor docker space available
  - Set `dm.basesize=100G` (TODO: still needed in this docker version?)
  - Set `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` (TODO: still needed?)
  - Set `ECS_AVAILABLE_LOGGING_DRIVERS` (TODO: still needed?)
  - Install new relic
  - Docker cleanup crons
  - `fstrim` cron
- [ ] Move CPU-credits monitor/killer to new cluster (perhaps CFN-ize?)

**Comment by cavis** [comment]
Done!
