### ISSUE TITLE
Migrate ID Staging

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#68]
ID Production currently lives on contegix.  But we can migrate ID-staging!

- [x] Setup aws-secrets
  - [x] Modify `bin/application` to _optionally_ read aws-secrets
  - [x] Setup staging secrets in S3 bucket
- [x] Add `.prxci`
- [x] Add prx app label to Dockerfile
- [x] Add to Infrastructure CD
- [ ] Bonus points: meta.prx.org acceptance tests

**Comment by pkarman** [comment]
What is the status of this ticket? @cavis @kookster

**Comment by cavis** [comment]
It's done!  http://id.staging.prx.tech/api/v1/certs
