### ISSUE TITLE
Log shipper for triton

### ISSUE THREAD

**Issue by kookster** [PRX/Infrastructure#684]
hearing from Jay Green that he's looking at using triton for audience analysis, and also to get into their ranker (we'd likely be in the top 10 if we do).

I haven't got the proposal yet, but sounds like a greater than 50% chance on this.

I believe this would be like magellan, and we'd add another log shipper configuration to go to a different s3 destination.

**Comment by kookster** [comment]
got more docs on this!
https://userguides.tritondigital.com/mea/pcmmg/podcast-log-req.html

**Comment by kookster** [comment]
this is still going through contracting - pushed it out a couple of sprints

**Comment by kookster** [comment]
Hearing from Jay @ Soundrise that they expect to get the contract done, and then try to get this live with Triton in June or July

**Comment by kookster** [comment]
Did a quick compare against a sample file
We don't have a hashed ip, just the listenerid
We have the range in 2 fields (start, end) not 1

So we'll go over those and see what might need to change

**Comment by farski** [comment]
Logs are being sent to (our) S3 bucket `prx-triton-cdn-logs`, and Triton should have access. No further work needed on our end, unless they ask for changes.
