### ISSUE TITLE
Set up TED feed cdn proxies (get them off feedburner)

### ISSUE THREAD

**Issue by kookster** [PRX/Infrastructure#723]
From Will:

> Thanks all for chatting today! Here's a list of [all of our feeds.](https://docs.google.com/spreadsheets/d/1JAIjvnaZYmOTKTq1zeHaFXdwsPYC847kSJkYXOqncN0/edit#gid=0) I've hidden some columns but left all of the info in there, in case it's helpful and you want to unhide. 
> 
> I'm most concerned w/ the first 20 feeds on this list. The next 8 feeds (in grey) are audio feeds but IP is owned by someone else (i.e Dylan Marron / Manoush) or they aren't hosted on PRX etc, so I'm going to take a beat to think about if we want to add them to our domain. 
> 
> The following ~220 feeds are a mess of video feeds that we need to internally do some vetting on. Let's pause that conversation till we know more about how many feeds we'll need there, but feel free to snoop around to see what they're like! 
> 
> For the first 20 I've added the URL labeling we'd like for each podcast, let me know what options have for domain names? Anything simple with TED would be great. 
> 
> Let me know when the feeds have been created (no rush, later next week is fine!), and we can go through looking at them / testing etc. 
> 
> Let me know if you have any questions!
> 
> Will

**Comment by farski** [comment]
Development work on this is done, and remaining work is being tracked elsewhere by tech distro.
