### ISSUE TITLE
Database VPC peering

### ISSUE THREAD

**Issue by cavis** [PRX/Infrastructure#78]
We use VPC peering to allow the CFN stacks to connect to our pre-existing RDS/Elasticache VPCs.

Here's how I've done this manually:

1. create a VPC “Peering Connection”, with the requester being our Platform-Staging VPC, and the accepter is the VPC redis resides in
2. go to the VPC route tables, and in the tables for _both_ VPCs, add a route destination to the Peering Connection you created
    ![image](https://user-images.githubusercontent.com/1410587/27752939-a0923290-5da0-11e7-9a35-9b44c2a044a3.png)
    (NOTE: this requires that your 2 VPCs have non-overlapping CIDRs)
3. in the redis security group (the one in EC2 console, not redis console), add an inbound rule for the ECS instance in the peer vpc
    ![image](https://user-images.githubusercontent.com/1410587/27752954-b5efecea-5da0-11e7-992d-97cd1a224143.png)

The “both” part of (2) was hanging me up for awhile.  if the redis vpc can’t route traffic back to the source, you’ll never get a connection.

**Comment by kookster** [comment]
seems like we have to figure out how to do this, with or without Cfn, and using multiple AWS accounts

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/peer-with-vpc-in-another-account.html
