### ISSUE TITLE
Investigate Parameter Store for secrets

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#94]
Seems like this is native support for most of what we're doing with Secrets: https://aws.amazon.com/ec2/systems-manager/parameter-store/

**Comment by farski** [comment]
https://segment.com/blog/the-right-way-to-manage-secrets/

**Comment by kookster** [comment]
This is helpful.
The one thing missing from our setup is being able to retrieve a set of secrets by a version guid, so we deploy secrets changes as we do code, and an instance runs with the same secrets values even if the latest value has been updated.

Could be this diff is not as important as it seemed, and we could switch to param store.

**Comment by farski** [comment]
https://aws.amazon.com/blogs/mt/the-right-way-to-store-secrets-using-parameter-store/

**Comment by kookster** [comment]
Marking as XL for estimate, including time to investigate, and change over existing build, and apps

**Comment by farski** [comment]
Merging work with #155
